### ISSUE TITLE
Feature Request - Kibana monitoring Failover

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-kibana-app#1280]
Hi team,

With the current Wazuh App configuration for HA environments where there is more than one Kibana instance, it's necessary to configure:
```yml
#In the 'master' Kibana instance: 
wazuh.monitoring.enabled: true
#In the other Kibana instances:
wazuh.monitoring.enabled: worker
```
If the instance configured as Master fails, the monitoring information will stop being indexed.

This makes it impossible to configure monitoring with High Availability.

I suggest adding some failover solution so the worker node would retrieve the monitoring information in case the 'master' Wazuh App is not working.

Best regards,
Miguel
