### ISSUE TITLE
[elastic-7] Configuration files

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1382]
Since Elastic 7, all the configuration files are broken or may be broken.

The point of this ticket is to make Wazuh compatible with Elastic 7 with no app installed.

Tasks:

- [x] Logstash
  - [x] Local
  - [x] Remote
- [x] Filebeat
- [x] Elasticsearch
- [x] Kibana

References:

- https://www.elastic.co/guide/en/logstash/current/index.html
- https://www.elastic.co/guide/en/beats/filebeat/current/index.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
- https://www.elastic.co/guide/en/kibana/current/index.html

Wazuh files:

- [logstash-local](https://github.com/wazuh/wazuh/blob/3.9/extensions/logstash/01-wazuh-local.conf)
- [logstash-remote](https://github.com/wazuh/wazuh/blob/3.9/extensions/logstash/01-wazuh-remote.conf)
- [filebeat](https://github.com/wazuh/wazuh/blob/3.9/extensions/filebeat/filebeat.yml)
- [elasticsearch](https://github.com/wazuh/wazuh/blob/3.9/extensions/elasticsearch/wazuh-elastic6-template-alerts.json)

**Comment by jesusgn90** [comment]
# Update 22/04/2019

> Fresh installation, CentOS 7 all-in-one instance

## Logstash

- Removed `document_type` from the output section. It's deprecated.
- Java is still **needed** for this component.

```rb
output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
    }
}
```

## Filebeat

- Replace `filebeat.prospectors`, it's deprecated, now we must use `filebeat.inputs`
- Removed `document_type`, it's deprecated.

```yml
filebeat.inputs:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

output:
 logstash:
   hosts: ["localhost:5000"]
```

Filebeat is now adding some fields starting with `agent.*`, that's in conflict with our key `agent` from alerts.

![image](https://user-images.githubusercontent.com/8860227/56508267-11995400-6524-11e9-9f81-071251cd27cc.png)

- Reference https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html#_agent_fields
- I've opened a ticket in https://discuss.elastic.co/t/field-named-agent-introduced-in-7-0-0-is-in-conflict-with-our-fields/177862/3 so we can know about the best solution for this behavior.

## Elasticsearch

- Java is **no longer needed** for Elasticsearch.
- The type has been deprecated, just removing it from our template worked for me.

**Before:**

```js
{
  ...
  "mappings": {
      "wazuh": {
      ...
      }
  }
}
```

**Now:**

```js
{
  ...
  "mappings": {
   ...
  }
}
```

My single node instance was configured using the next settings:

```yml
# /etc/elasticsearch/elasticsearch.yml 
cluster.name: "my-cluster"
node.name: "es-node-1"
node.master: true 
node.data: true
node.ingest: true
cluster.remote.connect: false
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.publish_host: localhost
discovery.zen.ping.unicast.hosts: ["localhost"]
```

## Kibana

- No Wazuh app yet
- Created an index pattern using Management > Index patterns worked for me.

![image](https://user-images.githubusercontent.com/8860227/56508628-0bf03e00-6525-11e9-81c1-ce88a6c48b9f.png)

This Kibana instance was configured using the next settings:

```yml
# Kibana is served by a back end server. This setting specifies the port to use.
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://localhost:9200"]
```

Here we can see a Discover screenshot from one of my testing environments:

![image](https://user-images.githubusercontent.com/8860227/56508643-1ad6f080-6525-11e9-837e-8fde7f08b622.png)

## Installation

All steps as before seem to be still valid, but it seems like we should review Logstash and Filebeat configuration files `permissions` and `owner:group` properties, my standard deployment scripts failed then I've increased those properties excessively (more than needed).

Some of the next steps that will be done shortly:

- Review Logstash/Filebeat configuration files `permissions` and `owner:group`.
- Solve the `agent.*` field conflict from Filebeat, also we must review all the ECS introduced fields.
- Create `wazuh/wazuh` branch for uploading all the configuration files modified.
- Ensure a clean installation is working as expected.

**Comment by jesusgn90** [comment]
# Update 23/04/2019

## Filebeat

After some researching, I've found a solution which prevents that Filebeat overwrites our field named `agent`. Here es the configuration:

```yml
filebeat.inputs:
  - type: log
    paths:
      - '/var/ossec/logs/alerts/alerts.json'

processors:
  - decode_json_fields:
      fields: ['message']
      process_array: true
      max_depth: 200
      target: ''
      overwrite_keys: true
  - drop_fields:
      fields: ['message', 'ecs']

output:
  logstash:
    hosts: ['localhost:5000']
```

As you can see, a `processor` has been adding, the trick here is that `processors` can handle the event before Filebeat adds its fields and here the `overwrite_keys` works as expected. All the ECS fields including `agent` are top-level fields, that's why it didn't work with the `json.overwrite_keys` attempt.

I've also closed the ticket https://discuss.elastic.co/t/field-named-agent-introduced-in-7-0-0-is-in-conflict-with-our-fields/177862 and I shared the solution so other users facing the same issue can handle the hit.

## Logstash

While fixing the Filebeat issue, I've noticed that we should add a new filter to our Logstash configuration files:

```rb
filter {
    if ![rule] {
        drop { }
    }
}
```

The above filter is intended to drop all events that have no `rule` as a required field. This way we are not indexing events that may have a similar structure as the Wazuh events, those events can be sent by some of the `beats` family from the Elastic stack.

**Comment by jesusgn90** [comment]
# Update 25/04/2019

Today I've added a second node to the Elasticsearch cluster, here is the config for both nodes:

```yml
# 1st node
cluster.name: "my-cluster"
node.name: "es-node-1"
node.master: true 
node.data: true
node.ingest: true
cluster.remote.connect: false
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 172.16.1.2 
cluster.initial_master_nodes: ["es-node-1"]

# 2nd node
cluster.name: "my-cluster"
node.name: "es-node-2"
node.master: false 
node.data: true
node.ingest: true
cluster.remote.connect: false
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 172.16.1.3 
discovery.seed_hosts:
   - 172.16.1.2 
cluster.initial_master_nodes: ["es-node-1"]
```

- `discovery.seed_hosts`, this setting was previously known as `discovery.zen.ping.unicast.hosts` ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/modules-discovery-settings.html#modules-discovery-settings)).
