### ISSUE TITLE
[elastic-7] How to reindex from 6.x to 7.x

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1383]
We need to determine a robust procedure to reindex events from Elastic 6.x to Elastic 7.x as we did for 5.x to 6.x.

This ticket may be in another repository, but we are the right team for researching reindex procedures.

What a reindex is?

> Take an index with a mapping named "A" and replace it with a new index which uses mapping "B". This new index must be compatible with the desired Elastic version and must not lose any information.

- [ ] Steps needed for reindexing a single index.
- [ ] Steps needed for reindexing from rotated `alerts.json` files.
- [ ] Pseudocode for a simple script that automates large re-indexations.

Regards

**Comment by juankaromo** [comment]
# Update 26/04/2019

Today I first reindexed a single index from 6.7.1 to 7.0.0 using remote:

Enable access to the remote host by adding it to the `reindex.remote.whitelist` in `elasticsearch.yml`
```rb
reindex.remote.whitelist: 172.16.1.2:9200
```
Reindex from remote 6.7 host to pull index into a new 7.0 index:
```yml
curl -X POST "localhost:9200/_reindex" -H 'Content-Type: application/json' -d'
{
  "source": {
    "remote": {
      "host": "http://172.16.1.2:9200",
      "username": "foo",
      "password": "bar"
    },
    "index": "wazuh-alerts-3.x-2019.04.17",
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "wazuh-alerts-3.x-2019.04.26"
  }
}
'
```

This works for me, and the output was:

```js
{"took":8386,"timed_out":false,"total":9022,"updated":0,"created":9022,"deleted":0,"batches":10,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}
```
