### ISSUE TITLE
Configuration filebeat

### ISSUE THREAD

**Issue by eowin** [wazuh/wazuh-kibana-app#1510]
| Wazuh | Elastic |
|-----------|----------|
|  3.9.1    |  7.1.0 |

Hi team,

I don't know if the issue that i encounter can be called a bug.

I have followed the documentation to setup filebeat and I see that you provide a filebeat.yml.

My Issue is that your configuration is working only in case you want only use ossec's logs in a specific index. That mean if I want to continue to receive my log in the index filebeat-XXXX it's not possible with your configuration.

Could you please help me to parse logs to have the following 'mechanic' : 
- Logs which come from /var/ossec/logs/alerts/alerts.json are automatically send to the good index (wazuh-alertsXXX)
- Default configuration logs of filebeat (/var/log/*.log) are automatically send to the filebeat-XXX's index

--------------------------
FYI I tried many thing like : 

```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

- type: log
  enabled: true
  paths:
    - /var/ossec/logs/alerts/alerts.json

setup.template.json.enabled: true
setup.template.json.path: "/etc/filebeat/wazuh-template.json"
setup.template.json.name: "wazuh"
setup.template.overwrite: true

processors:
  - decode_json_fields:
      fields: ['message']
      process_array: true
      max_depth: 200
      target: ''
      overwrite_keys: true
  - drop_fields:
      fields: ['message', 'ecs', 'beat', 'input_type', 'tags', 'count', '@version', 'log', 'offset', 'type', 'host']
  - rename:
      fields:
        - from: "data.aws.sourceIPAddress"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.aws.sourceIPAddress: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
  - rename:
      fields:
        - from: "data.srcip"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.srcip: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
  - rename:
      fields:
        - from: "data.win.eventdata.ipAddress"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.win.eventdata.ipAddress: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
....
....
output.elasticsearch:
  hosts: ['http://YOUR_ELASTIC_SERVER_IP:9200']
  indices:
    - index: 'wazuh-alerts-3.x-%{+yyyy.MM.dd}'
      when.equals:
        paths: /var/ossec/logs/alerts/alerts.json
```

When I try this, My elasticsearch log is hardly spammed with java errors (but filebeat start and elasticsearch start too)

Thank you for your help, I'm blocked on this since many days and didn't found subject on internet which is able to help me...

**Comment by eowin** [comment]
HI @jesusgn90 

Thank you for your response.

Do you think the following configuration can work correctly ?

```
filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log
    fields:
      origin: "filebeat-%{[agent.version]}"
  - type: log
    paths:
      - /var/ossec/logs/alerts/alerts.json
    fields:
      origin: "wazuh-alerts-3.x"
...
...
output.elasticsearch:
  hosts: ['http://xx.xxx.xx.xx:9200']
  indices:
    - index: '%{[fields.origin]}-%{+yyyy.MM.dd}'
```

Or you maybe have a better idea ?

**Comment by jesusgn90** [comment]
Hello again @eowin ,

That won't work, however, here is a different solution for achieving your goal properly:

```yml
filebeat.inputs:
  - type: log
    paths:
      - /var/log/messages
    fields:
      origin: "filebeat"
  - type: log
    paths:
      - /var/ossec/logs/alerts/alerts.json
    fields:
      origin: "wazuh-alerts-3.x"

...

output.elasticsearch:
  hosts: ['http://xx.xx.xx.xx:9200']
  indices:
    - index: '%{[fields.origin]}-%{+yyyy.MM.dd}'
      when:
        equals:
          fields.origin: "wazuh-alerts-3.x"
    - index: '%{[fields.origin]}-%{[agent.version]}-%{+yyyy.MM.dd}'
      when:
        equals:
          fields.origin: "filebeat"
```

The above solution works including the data you are looking for.

How this solution works:

- Filebeat 7.1.1 reading `/var/log/messages` and reading `/var/ossec/logs/alerts/alerts.json`
- An event from `/var/log/messages` comes, it has `fields.origin: filebeat`, then it will be sent to the index named `'%{[fields.origin]}-%{[agent.version]}-%{+yyyy.MM.dd}'` which would be `'filebeat-7.1.1-2019.06.07'`
- An event from `/var/ossec/logs/alerts/alerts.json` comes, it has `fields.origin: wazuh-alerts-3.x`, then it will be sent to the index named `'%{[fields.origin]}-%{+yyyy.MM.dd}'` which would be `'wazuh-alerts-3.x-2019.06.07'`

I hope it helps.

Regards,
Jesús

**Comment by eowin** [comment]
Hi @jesusgn90,

Thank you for your help, i'll try your solution, I come back to you later to give you my feedback about your solution :)

**Comment by eowin** [comment]
@jesusgn90 

I did some test, I receive many data, and that look working fine for wazuh,  but for the index filebeat data looks incorrect, I suspect this an issue which come from the json configuration for wazuh :



@timestamp | Jun 7, 2019 @ 12:45:29.549
-- | --
t _id | vkmLMWsBCHD5z3QpNjq_
t _index | filebeat-7.1.0-2019.06.06-000002
# _score | -
t _type | _doc
t agent.ephemeral_id | b3222601-7f92-4119-bd47-661385b0b066
t agent.hostname | elastic30
t agent.id | 56bf5ef7-e9d1-4f08-a5ab-05c405dfbcf9
t agent.type | filebeat
t agent.version | 7.1.0
t error.message | **field [message] not present as part of path [message]**
t event.dataset | system.auth
t event.module | system
t fileset.name | auth
t input.type | log
t service.type | system
suricata.eve.timestamp | Jun 7, 2019 @ 12:45:29.549

Do you have an idea ?

**Comment by jesusgn90** [comment]
Yes, probably caused by not ignoring the processor blocks.

For example:

```yml
  - drop_fields:
      fields: ['message', 'ecs', 'beat', 'input_type', 'tags', 'count', '@version', 'log', 'offset', 'type', 'host']
```

Must be replaced with:

```yml
  - drop_fields:
      when.equals.fields.origin: wazuh
      fields: ['message', 'ecs', 'beat', 'input_type', 'tags', 'count', '@version', 'log', 'offset', 'type', 'host']
```

The added line is:

```yml
      when.equals.fields.origin: wazuh
```

Otherwise, all events will pass through those processors and you want that just for Wazuh events but not for the rest.

I hope it helps.

Kind regards,
Jesús
