### ISSUE TITLE
Hide/Block the Wazuh app depending on the selected Kibana space

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1601]
**Describe the solution you'd like**
Certain complex environments are using custom spaces from Kibana, users want to restrict/filter the usage of the Wazuh app depending on the user's active space.

**Describe alternatives you've considered**
- Explore spaces feature, we might achieve it with no development.
- If the first idea doesn't work, let's develop some code in the Wazuh app for blocking users depending on the active space. This will probably be the solution.

Since we don't know the effort for this task yet, we can't tell you which version will be the release for this feature, however, I think we can reach it for the next minor (3.10) where the app is compatible with custom spaces. Stay updated tracking this ticket.

**Comment by jesusgn90** [comment]
Here is a tiny follow up about this task:

After some researching and with a 3.10 app (which is compatible with custom spaces), we've concluded that we may want to add a new setting for the `config.yml` file.

This new setting would be an array of namespaces, that's said, it would look like the next block by default (allow all spaces):

```yml
#spaces.allowed: ['*']
```

Possible customizations would be:

```yml
spaces.allowed: ['*'] --> all spaces are allowed
spaces.allowed: [ ]   --> same as '*' ?
spaces.allowed: ['default', 'staging'] --> only 'default' and 'staging' spaces are allowed
spaces.allowed: ['staging', '*'] --> all spaces are allowed ?
spaces.allowed: [-1, null, 'foo'] --> invalid content, all spaces are allowed? just the 'default' space is allowed?
```

The easy way would be to make the app be still visible, but users wouldn't see anything inside the app if their spaces are not allowed, something similar to the index patterns lock we are doing with X-Pack.

Another way would be to fully hide the Wazuh app, but I'm not sure if this would be possible from the app itself (the app would hide the app...).

Regards
