### ISSUE TITLE
Only randomly selective alerts end up in the Kibana/elasticsearch.

### ISSUE THREAD

**Issue by kovaga** [wazuh/wazuh-kibana-app#2248]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.3-1 | 7.6.2| |

**Description**
Short description of your issue.

Somehow not all alerts are being added into elasticsearch and displayed in kibana.

**Steps to reproduce**
I setup a who-data monitored directory
`<directories check_all="yes" whodata="yes">/home/fim_test</directories>`

run the following command to generate a file every minute
`# while :; do touch /home/fim_test/file_`date +%H%M`; sleep 60; done`

The alerts are generated on the wazuh-manager for each created file
```
** Alert 1590510431.907636: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 May 26 18:27:11 (s1.kos.home) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/fim_test/file_1827' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue May 26 18:27:10 2020
 - Inode: 3282
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: gkos
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 5059
 - (Audit) Process name: /bin/touch
```
However, in the last 20 minutes of running the file creation script, I can see only 4 entries being added in the Elastic search, despite 20 files and alerts were generated.
```
# cat /tmp/Alerts\ summary.csv                                                                                                                                                                        
File,Description,Count
"/home/fim_test/file_1817","File added to the system.",1
"/home/fim_test/file_1821","File added to the system.",1
"/home/fim_test/file_1826","File added to the system.",1
"/home/fim_test/test-1812","File added to the system.",1
```
Doesn't look like a normal behaviour or is there some sort of limit on number of processed events in the opensource version or did I simply forget to configure something?

At the moment only one test agent is conected to the wazuh-manager.

UPDATE
I've left the file creation command running overninght, and observed that on average the number of reported items were in 20 to 30 range, out of 60 events created.
Another strange observation is the time of appearance of events in Kibana were delayed from 3 to 10 minutes after the alert was generated.
