### ISSUE TITLE
SCA checks without compliance field can't be expanded

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-kibana-app#2264]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13.0   | 7.6.2 | 0870 |

**Description**
Hi team,

SCA allows creating rules without `compliance` field (see [SCA checks](https://documentation.wazuh.com/3.12/user-manual/capabilities/sec-config-assessment/creating_custom_policies.html#sca-policy-file-checks-section)). So, while I was creating a custom SCA file, I can't expand those rules without this field in the SCA section of the agent.

If you want to reproduce it, add this rule to any SCA file:
```yaml
  - id: 7101
    title: "Ensure ufw is installed"
    description: "ufw the default firewall manager in Ubuntu and can be installed in your Raspberry Pi to help you to set up the firewall rules"
    rationale: "A firewall is a network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules. ufw uses iptables to set up the firewall but with less complicated rules. This will filter your network traffic and block non-desired or malicious traffic."
    remediation: "Install ufw using the following command. # apt install ufw"
    references:
      - 'https://www.raspberrypi.org/documentation/configuration/security.md'
    condition: none
    rules:
      - 'c:dpkg -s ufw -> r:install ok installed'
```

**Steps to reproduce**

1. Go to `Security configuration assessment`.
2. Select the agent with the rule from above.
3. Select the policy with the rule from above.
4. Try to expand the rule to get more info:

**Screenshots**
- Rule without `compliance`: ![image](https://user-images.githubusercontent.com/9081114/84661526-c8bc1000-af1a-11ea-8279-7e45ec66a892.png)
- Rule with `compliance`: ![image](https://user-images.githubusercontent.com/9081114/84662084-9959d300-af1b-11ea-8d6b-b50ff97bea0c.png)

**Additional context**
- Wazuh Manager: Ubuntu 16.04
- Environment: The Wazuh Manager and ELK run in Docker containers.
- Agent: Raspbian GNU/Linux 10 (buster)
- Browser: Mozilla Firefox 77.0.1
