### ISSUE TITLE
Wazuh_user can't access to Wazuh Kibana plugin

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-kibana-app#2467]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.0   | 7.8.0 Open Distro     | [Wazuh Kibana plugin pre-release](https://packages-dev.wazuh.com/pre-release/ui/kibana/wazuh_kibana-4.0.0_7.8.0-1.zip) |

**Description**
Hello team! 

After doing an installation, both all-in-one deployment and distributed deployment, I haven't been able to access the Wazuh Kibana plugin using the `wazuh_user` but I had no problem using the `wazuh_admin` user.

**Steps to reproduce**

This behavior happens with any kind of deployment, all-in-one or distributed and with any type of installation, unattended or step-by-step. I'll use the all-in one unattended installation as an example:

1. Install an all-in-one using [this script](https://github.com/wazuh/wazuh-documentation/blob/2205-Open_Distro_installation/resources/open-distro/unattended-installation/all-in-one-installation.sh).
2. Enter Kibana and log in using as credentials `wazuh_user`. It won't let you access the Wazuh Kibana plugin (screenshot 1).
3. Enter Kibana and log in using as credentials `wazuh_admin`. It will let you access the Wazuh Kibana plugin (screenshot 2).

**Screenshots**
![image](https://user-images.githubusercontent.com/60152567/93365022-8cfe5280-f849-11ea-97ce-517acbdadb1f.png)
![image](https://user-images.githubusercontent.com/60152567/93365390-05651380-f84a-11ea-9909-dfc9f2bf16fe.png)

**Additional context**

This is the configuration of the roles and users added:

- `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml`

```
wazuh_ui_admin:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
    - "delete"
    - "manage"
    - "index"
  tenant_permissions: []
  static: false
alerting_view_alerts:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - ".opendistro-alerting-alert*"
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
  tenant_permissions: []
  static: false
wazuh_ui_user:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
  tenant_permissions: []
  static: false
```

- `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml`

```
wazuh_ui_admin:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
  - "wazuh_admin"
  and_backend_roles: []
wazuh_ui_user:
  reserved: true
  hidden: false
  backend_roles: []
  hosts: []
  users:
  - "wazuh_user"
  and_backend_roles: []
wazuh_ui:
  reserved: false
  hidden: false
  backend_roles: []
  hosts: []
  users:
  - "kibanaserver"
  and_backend_roles: []
```

- `/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml `

```
wazuh_admin:
  hash: "$2y$12$d2awHiOYvZjI88VfsDON.u6buoBol0gYPJEgdG1ArKVE0OMxViFfu"
  reserved: true
  hidden: false
  backend_roles: []
  attributes: {}
  opendistro_security_roles: []
  static: false
wazuh_user:
  hash: "$2y$12$BQixeoQdRubZdVf/7sq1suHwiVRnSst1.lPI2M0.GPZms4bq2D9vO"
  reserved: true
  hidden: false
  backend_roles: []
  attributes: {}
  opendistro_security_roles: []
  static: false
```

Regards,

David

**Comment by pablotr9** [comment]
Hi @davidfmiranda ,

Apart from read permissions over `wazuh-*` indices, the `wazuh_user` also needs minimum permissions to use Kibana. This means that is should have permissions to manage`.kibana*`, `.tasks*` and some other indices. 

The easiest way is to add the role `kibana_user` to the `wazuh_user`. (This `kibana_user` is one of the predefined roles that  comes by default with Opendistro)
It can be done by simply editing the `kibana_user` entry in the `roles_mapping.yml` file, it should look like this:
```
kibana_user:
  reserved: false
  backend_roles:
  - "kibanauser"
  description: "Maps kibanauser to kibana_user"
  users:
  - "wazuh_user"
```
