### ISSUE TITLE
Change Wazuh API default user from wazuh to wazuh-wui

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-kibana-app#2852]
I suggest changing the default API credentials from `wazuh` to `wazuh-wui` as this user has  [default rules](https://documentation.wazuh.com/4.0/user-manual/api/rbac/reference.html#default-rules) that map administrator permissions for the default Elastic and Open Distro users making the RBAC experience more user-friendly.
```
hosts:
  - default:
     url: https://localhost
     port: 55000
     username: wazuh-wui
     password: wazuh-wui
     run_as: false
```
