### ISSUE TITLE
Extensions added in wazuh.yml not working

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-kibana-app#3640]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.0   | 7.10.2    | 4201-11 | ODFE |

| Browser |
| ------- |
| Chrome|

**Description**
I have made some changes to the `wazuh.yml` in order to add the AWS and Docker extensions. Those changes did not take effect so I enabled those modules in the Kibana Web UI to make it work. Example of the file:
```
# BEGIN ANSIBLE MANAGED BLOCK
hosts:
  - env-1:
     url: https://IP1
     port: 55000
     username: wazuh
     password: wazuh
     run_as: false
     extensions.aws: true
     extensions.docker: true
  - env-2:
     url: https://IP2
     port: 55000
     username: wazuh
     password: wazuh
     run_as: false
     extensions.aws: true
     extensions.docker: true
# END ANSIBLE MANAGED BLOCK
```
Reviewing the files located in /usr/share/kibana/data/wazuh/config I realized that the change in the Web UI had impacted in the `wazuh-registry.json`.

The issue is that the documentation does not say anything about that file (`wazuh-registry.json`):
https://documentation.wazuh.com/current/user-manual/kibana-app/reference/config-file.html#extensions-docker

The change works If I modify the `wazuh-registry.json` to enable those modules or if I enable them using the Kibana Web UI. But I need to automate it so the Kibana method is not an option.

**Preconditions**
1. Configure a new Demo Environment.
2. The Demo Env. has the following architecture:
![MultitenantWazuh](https://user-images.githubusercontent.com/33964202/135484133-37d052b9-e629-444c-834e-715534fa1224.png)

**Steps to reproduce**
1. Modify the wazuh.yml in the Wazuh Kibana App installation.
2. Login to Kibana and go the Modules directory
3. The AWS and Docker extensions are not being showed.

**Expected Result**
1. The AWS and Docker being listed:
![Screenshot from 2021-09-30 12-23-51](https://user-images.githubusercontent.com/33964202/135484594-17b23fb6-499a-4d64-b028-9dceb7bda624.png)

**Actual Result**
1. Modules directory without those links:
![Screenshot from 2021-09-30 12-25-18](https://user-images.githubusercontent.com/33964202/135484781-d3df88f8-f0c5-4fa0-b25b-405f5f2edff8.png)

**Comment by yenienserrano** [comment]
The extensions configuration is not divided by host, it is a global configuration, so to see the extensions you want when new hosts are added, you have to configure it outside the host configurations at the same level as the word hosts.

**for example:**

```
hosts:
  - env-1:
     url: https://IP1
     port: 55000
     username: wazuh-wui
     password: wazuh-wui
     run_as: true
  - env-2:
     url: https://IP2
     port: 55000
     username: wazuh-wui
     password: wazuh-wui
     run_as: true

extensions.aws: true
extensions.docker: true 
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/63758389/177959872-ab766e89-867d-4628-a194-b79afdf3720f.png)
