### ISSUE TITLE
Include GitHub Actions to run the tooling

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4681]
## Description

As part of #4579, we'll include GitHub actions to run ESLint and similar tools to enhance the code quality.

We need to read about GitHub actions and its [Code Scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) features.

Depends on: #4640 (tooling base) and #4680 (re-usable workflows)

**Comment by AlexRuiz7** [comment]
Information about GitHub actions

https://docs.github.com/en/actions
https://docs.github.com/es/actions/learn-github-actions/understanding-github-actions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

_Originally posted by @yenienserrano in https://github.com/wazuh/wazuh-kibana-app/issues/4665#issuecomment-1276015784_

**Comment by AlexRuiz7** [comment]
We currently have two approaches to achieve this:

- Using a custom workflow (based on https://github.com/wazuh/wazuh-kibana-app/pull/4680):
```yaml
# This workflow calls to `reusable-dev-environment` workflow to run do unit tests

name: Check - Code integrity

on:
  workflow_dispatch:
    inputs:
      reference:
        required: true
        type: string
        default: master
        description: Branch/Tag/Commit SHA reference for the source code.
  pull_request:
    branches:
      - 'main'
      - 'master'
      - '*.*-*.*'
      - '*.*-*.*-wzd'

jobs:
  check-code-integrity:
    name: Deploy a dev environment and check the code integrity
    uses: ./.github/workflows/reusable-dev-environment.yml
    with:
      reference: ${{ github.event.inputs.reference || github.ref }}
      command: '(find node_modules/.bin/eslint && yarn lint || "../../node_modules/.bin/eslint" .)'
    secrets: inherit
```

- Using the official GitHub Action to run ESLint (adapted):
```yaml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches: [ "master", "*.*-*.*", "*.*-*.*-wzd" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "*.*-*.*", "*.*-*.*-wzd" ]
  # schedule:
  #   - cron: '28 18 * * 0'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          yarn
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: yarn lint
          --format @microsoft/eslint-formatter-sarif 
          --output-file eslint-results.sarif
        # run: npx eslint {public,server,common}
        #   --config .eslintrc.json
        #   --ext .js,.jsx,.ts,.tsx,.json
        #   --format @microsoft/eslint-formatter-sarif 
        #   --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
```

Official tools are always preffered, if possible.
