### ISSUE TITLE
OpenID Connect setup cannot handle backend roles

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh-kibana-app#4781]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
4..9 | Wazuh-Indexer | N/A | Basic

| Browser |
| ------- |
| N/A

**Description**
When OpenID Connect is set up, the roles_mapping.xml does not handle the mapping for OIDC roles.

**Preconditions**
1. Install Wazuh 4.3.9 using Wazuh-Indexer and Wazuh-Dashboard.
2. Have a OIDC Provider, e.g. Keycloak.
3. Set up OpenID Connect according to the documents [OpenSearch documents](https://opensearch.org/docs/latest/security-plugin/configuration/openid-connect/).
4. Create roles, e.g. `admin` and `operator` on OIDC provider.
5. Set up the Wazuh confoguration to match (details below)

**Steps to reproduce**
1. Log in to Wazuh using OIDC SSO credentials.

**Expected Result**
1. User gets to see the dashboard based on access toles

**Actual Result**
1. User gets an error message that user has no backend roles mapped, hence no permissions.

**Screenshots**
![auth_admin_master_console](https://user-images.githubusercontent.com/39981909/198972691-8d6f98a0-d9c4-4e11-b92c-abb4a726db44.jpg)
_General setup_

![OIDC roles](https://user-images.githubusercontent.com/39981909/198971706-50745638-3350-4044-a908-b8883d6968be.png)
_OIDC Roles_

![Default Scopes](https://user-images.githubusercontent.com/39981909/198971863-8814e5f3-0d43-4ac1-8b08-da7424d958fb.png)
_Default Scopes_

![Error screen](https://user-images.githubusercontent.com/39981909/198968753-d475dbe0-3e4e-409d-85be-27d65f4c54c6.png)
_Error screen_

**Additional context**
_/etc/wazuh-dashboard/opensearch_dashboards.yml_
```yaml
# OpenID Setup
# Enable OpenID authentication
opensearch_security.auth.type: "openid"

# The IdP metadata endpoint
opensearch_security.openid.connect_url: "https://<OIDC provider>/auth/realms/<realm>/.well-known/openid-configuration"

# The ID of the OpenID Connect client in your IdP
opensearch_security.openid.client_id: "wazuh-test-oidc"

# The client secret of the OpenID Connect client
opensearch_security.openid.client_secret: "secret"

# Configure the Kibana internal server user
opensearch.username: "kibanaserver"
opensearch.password: "password"

# Disable SSL verification when using self-signed demo certificates
opensearch.ssl.verificationMode: none
opensearch_security.openid.verify_hostnames: "false"

# Add roles to the scope (default value: openid profile email address phone)
# Needed when you add another scope to the clients
opensearch_security.openid.scope: "openid profile email address phone roles"
```

_/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/config.yml_
```yaml
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://<OIDC provider>/auth/realms/<realm>/.well-known/openid-configuration
        authentication_backend:
          type: noop
```
_/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/roles_mapping.yml_
```yaml
...
all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  - "wazuh-admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Maps admin to all_access"
...
readall:
  reserved: true
  hidden: false
  backend_roles:
  - "readall"
  - "wazuh-ro"
  hosts: []
  users: []
  and_backend_roles: []
...
kibana_user:
  reserved: false
  hidden: false
  backend_roles:
  - "kibanauser"
  - "wazuh-operator"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Maps kibanauser to kibana_user"
...
```

**Comment by Tostti** [comment]
Hi @zbalkan , 

To be able to have the backend roles configured and successfully sent to wazuh-dashboard, you need to follow these steps:

1. Create the desired roles in your realm's `roles` tab. In this example I will use the roles `admin` and `all_access`:
![image](https://user-images.githubusercontent.com/42900763/199033000-ed8c2be7-187c-4d8d-abff-685c349e4ff4.png)

2. Add those roles to the user that you will use to log in from the `users` tab of your realm, and the `Role mappings` tab of your user. In this example, the user is `wazuh`: 
![image](https://user-images.githubusercontent.com/42900763/199033909-efc3af36-add2-4624-90cb-3c2f622464c8.png)

3. Inside your client configuration, go to `mappers` and select `realm_roles`. Inside that, you will see a field named `Token Claim Name`. That field is the name that should go on `roles_key` inside your `config.yml`. 
![image](https://user-images.githubusercontent.com/42900763/199034802-59ad22e7-886d-4109-a49b-38ab6ccf4b74.png)
![image](https://user-images.githubusercontent.com/42900763/199034957-1ae9073b-a62b-4a19-99c1-f41b81ec6ae7.png)

In this example the Token Claim Name is `role`, and therefore the `config.yml` file should contain that name. For example
```
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: role
            openid_connect_url: https://<OIDC provider>/auth/realms/<realm>/.well-known/openid-configuration
        authentication_backend:
          type: noop

```

With that configuration, you will be able to see the backend roles once you log in
![image](https://user-images.githubusercontent.com/42900763/199035687-5e78f1a6-f7a0-4cbe-a553-0f62253fbe2d.png)

I hope you find this information helpful.
Regards,
