### ISSUE TITLE
[BUG] Inconsistent Data Refresh Behavior in Dashboard Table Accordion

### ISSUE THREAD

**Issue by Yaren-IT** [wazuh/wazuh-kibana-app#7543]
**Issue Description**
When using the Wazuh dashboard's event table accordion, I've noticed an inconsistency in data refresh behavior. Specifically, upon clicking the "Refresh" button, the data within the accordion table does not update dynamically. Instead, the displayed content remains static until the accordion is closed and reopened, at which point the updated data is reflected.

Interestingly, this behavior contrasts with the automatic refresh of the "Result" column, where it dynamically transitions from "Failed" with a red dot to "Passed" with a green dot without requiring manual intervention.

**To Reproduce**

0. Define your individual SCA rule in which you check for the presence of a string in a file, but do not create the file (status is then not applicable)
1. Open the Wazuh dashboard.
2. Navigate to the event table accordion.
3. Observe the data within the accordion.
4. Now create the file in the host on which the agent is installed so that the status changes from not applicable to Passed (or failed, depending on the check).
6. Click the "Refresh" button.
7. Note that the data does not update dynamically.
8. Close and reopen the accordion.
9. Observe that the updated data is now reflected.

**Expected behavior**
Upon clicking the "Refresh" button, the data within the event table accordion should update dynamically without requiring manual closure and reopening of the accordion.

**Impact**
This inconsistency in data refresh behavior affects user experience and may lead to confusion regarding the real-time status of events within the dashboard. Resolving this issue would enhance the usability and reliability of the Wazuh dashboard for users relying on up-to-date event information.

**Comment by Desvelao** [comment]
# Replicate

I could replicate the problem in a current Wazuh dashbiard (v4.12.0), following the commented steps:

0. Define the following SCA policy:

<details>

<summary>SCA policy</summary>

Create the following policy in the Wazuh agent host at `/var/ossec/ruleset/sca/custom_policy.yml`.

```yml
# Security Configuration Assessment
# Audit for UNIX systems
# Copyright (C) 2015, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation

policy:
  id: "custom_policy"
  file: "custom_policy.yml"
  name: "Custom policy"
  description: "Custom policy description"

checks:
  - id: 50000
    title: "Ensure the /tmp/test file contains test string"
    description: "Ensure the /tmp/test file contains test string."
    rationale: "Test."
    remediation: "Create a file that contains the test string in /tmp/test"
    compliance:
      - pci_dss: ["2.2.4"]
      - nist_800_53: ["CM.1"]
    condition: all
    rules:
      - 'f:/tmp/test -> r:test'
```

1. Open the Wazuh dashboard.
2. Navigate to the event table accordion.
3. Observe the data within the accordion.

</details>

3. Review the check in the SCA Dashboard table ensuring this is not applicable

![Image](https://github.com/user-attachments/assets/cc5b624e-23a4-4b19-830e-e01811e88ae2)

4. Now create the file in the host on which the agent is installed so that the status changes from not applicable to Passed (or failed, depending on the check). 

With the expanded row related to the check, go to the agent and apply some changes to cause the check changes of status (passed or failed it this was not applicable)

```console
[root@vbox sca]# echo "test" > /tmp/test
[root@vbox sca]# cat /tmp/test
test
```

Wait for the following SCA scan or force it restarting the agent if this is configured to run at starting.

5. Click the "Refresh" button

6. Note that the data does not update dynamically.

![Image](https://github.com/user-attachments/assets/36f915d8-7b78-43cc-b2c3-81c824b21d49)

7. Close and reopen the accordion.
8. Observe that the updated data is now reflected.

![Image](https://github.com/user-attachments/assets/dd932009-5850-4c61-a038-f7565ceec6d6)

# Conclusion

This seems to be a minor bug that has special importance when the user expects to see the recent data using the `Refresh` button.
